name:                hs-TAPL-impl
version:             0.1.0.0
github:              "hiratara/hs-TAPL-impl"
license:             BSD3
author:              "Masahiro Honma"
maintainer:          "hiratara@cpan.org"
copyright:           "hiratara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hiratara/hs-TAPL-impl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hs-TAPL-impl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-TAPL-impl

tests:
  hs-TAPL-impl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-TAPL-impl
